# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59d66530b45c5b2022d86de963685ac9340ae2f3cf75bc5cf5923dd01e5b52c45074ba1544d5b2905ab23bd46e0c6b1cd79b36f15068de23ce6d57950d979432

test:
  secret_key_base: 5c4b8ce7313ec3ee6f14f5c82c0bfaabb532219a3ee51e4a4587c4e0b523ea0cc380ca0d2e3d75d4eca904eb40f847006c4093d4aaa9d239f0fa42516690b723

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
